<a href="https://colab.research.google.com/github/Xander50/PRO-124/blob/main/Copy_of_PRO_124_Project_Boilerplate_Code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Print Elements of Array

**Problem**: Given 1X1 Array:

```
arr_1d = [53, 78, 90, 12, 15, 65, 44, 32, 29, 36]
```

1. Print 3rd and 9th element of the array.
2. Change  3rd and 9th element to 100.


In [3]:
import numpy as np
arr_1d = np.array([53, 78, 90, 12, 15, 65, 44, 32, 29, 36])
print(arr_1d[2])
print(arr_1d[8])
arr_1d[2]=100
arr_1d[8]=100
print(arr_1d)


90
29
[ 53  78 100  12  15  65  44  32 100  36]


## Update Diagonal Elements of Multidimensional Array

**Problem**: Given a 3x3 array, change all the diagonal elements of the matrix to 0.

```

arr_2d = [[1,2,3],
          [4,5,6],
          [7,8,9]]
```





In [4]:
#Write code here
arr_2d = np.array([[1,2,3],
          [4,5,6],
          [7,8,9]])
rows=3
cols=3

for i in range(rows):
  for j in range(cols):
    if i==j:
      arr_2d[i][j]=0
    else:
      pass
print(arr_2d)


[[0 2 3]
 [4 0 6]
 [7 8 0]]


## Numbers of Rows & Column

**Problem**: Write a program to find the number of rows and columns present in the matrix given below. 
Note: Initialize the matrix using NumPy.

```
 A= [[9,5,6,1,-2],
    [3,-8,1,2,0],
    [6,9,3,3,5]]
```



In [6]:
# write code here
A= np.array([[9,5,6,1,-2],
    [3,-8,1,2,0],
    [6,9,3,3,5]])
rows,columns=A.shape
print("number of rows:",rows)
print("number of columns:",cols)

number of rows: 3
number of columns: 5


## Scalar Multiplication

**Problem**: Print each element of the following matrix. Initialize the matrix using NumPy.  <br />
Also, multiply the matrix with n = 150 and print the matrix after multiplication.
   
```
 B=[[-8,0,2,4],[5,2,-1,7]]
```


   

In [4]:
import numpy as np
B=np.array([[-8,0,2,4],[5,2,-1,7]])
n=150
rows=len(B)
cols=len(B[0])
mul=np.zeros([rows,cols])
count=1
for i in range(rows):
  for j in range(cols):
    mul[i][j]=n*B[i][j]
    if count<=n:
      print("element",count,"is",B[i][j])
      count+=1
print("\n",mul)
  

element 1 is -8
element 2 is 0
element 3 is 2
element 4 is 4
element 5 is 5
element 6 is 2
element 7 is -1
element 8 is 7

 [[-1200.     0.   300.   600.]
 [  750.   300.  -150.  1050.]]
